version: '1.0'

services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/wanderlust
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
